### PR TITLE
hardening/370_utc_timestamp

### PR DESCRIPTION
**Pull request by frbattid**
* Fixes issue https://github.com/telefonicaid/fiware-cygnus/issues/370
* 100% unit tests passed
```
Results :
Tests run: 48, Failures: 0, Errors: 0, Skipped: 0
```
* Assignee @gtorodelvalle but LGTM from @fgalan is also required

### CODE REVIEW

**Comment by fgalan** [comment]
LGTM (passing the ball to @gtorodelvalle for final LGTM + merge + delete branch)

**Comment by gtorodelvalle** [comment]
Hi guys! Just a comment regarding the dates of the shape "2014-02-27T14:46:21UTC". That format does not comply to the ISO ISO 8601 specification (ISO Date and Time format). As you can see here: http://es.wikipedia.org/wiki/ISO_8601#Hora_UTC , UTC dates and times end in "Z" and not in UTC. This is the format used in the STH component :)

**Comment by frbattid** [comment]
UTC issue fixed in https://github.com/telefonicaid/fiware-cygnus/commit/a549268f3ad8bf16b91f4e8b8e0f5d9df7eb573d

**Comment by gtorodelvalle** [comment]
Thanks @frbattid ! LGTM! :)

**Pull request merged**
