### PR TITLE
Feature/1516 create elasticsearchsink

### LINKED ISSUE #1516: [cygnus-ngsi][feature][NGSIElasticsearchSink] create NGSIElasticsearchSink
I want to use cygnus-ngsi with [Elasticsearch](https://www.elastic.co/products/elasticsearch). So I wrote conceptual implementations like below:

* `com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSink`
* `com.telefonica.iot.cygnus.backends.elasticsearch.ElasticsearchBackend`
* `com.telefonica.iot.cygnus.backends.elasticsearch.ElasticsearchBackendImpl`

What do you think about "ElasticsearchSink"? If you are interested in, I will write tests and documents and contribute this.

### PR DESCRIPTION
**Pull request by nmatsui**
resolve #1516 #1521

I wrote and unit-tested the NGSIElasticsearchSink and ElasticsearchBackendImpl. 
Please check this pull request and please approve this if you think good.

# feature
## [cygnus-common] com.telefonica.iot.cygnus.backends.elasticsearch.ElasticsearchBackendImpl
* This class extends HttpBackend.
* `bulkInsert()`
    * This method stores the data to Elasticsearch as one or more document(s) using its REST API . The document's index is created automatically if absent it.
    * Multiple documents can be stored at one time.
    * The "recvTimeTs" and hash (md5) of document are used to generate an unique document id.

## [cygnus-ngsi] com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSink
* This class extends NGSISink.
* The configurable variables are below:

|variable|default|constraint|description|
|:---|:---|:---|:--|
|elasticsearch_host|localhost||the hostname of Elasticsearch server|
|elasticsearch_port|9200|0 ~ 65535|the port number of Elasticsearch server|
|ssl|false|"true" or "false"|"true" if connect to Elasticsearch server using SSL|
|index_prefix|cygnus||the prefix of index name|
|mapping_type|cygnus_type||the mapping type name|
|backend.max_conns|500|integer|the max connections to be used by HttpClient|
|backend.max_conns_per_route|100|integer|the max connections per route to be used by HttpClient|
|ignore_white_spaces|true|"true" or "false"|"true" if ignore an empty value|
|attr_persistence|row|"row" or "column"|the persistence style as row-style or column-style|
|timezone|UTC||timezone to be used as a document's timestamp|
|cast_value|false|"true" or "false"|"true" if cast the attrValue using attrType|
|cache_flash_interval_sec|0|integer|the interval (sec) to flash memory cache|

* The index name of Elasticsearch is like below:
    * <<index_prefix>>-<<FIWARE_SERVICE>>-<<FIWARE_SERVICEPATH>>-<<yyyy.mm.dd>>
* Like NGSIMongoSink, the "row-style" and "column-style" are selectable.
* Like NGSIMongoSink, the "ignore_white_spaces" is configurable.
* If `cache_flash_interval_sec` is not zero, the aggregated data is cached on memory and the cached data will be persisted periodically altogether at the specified intervals.

## Dockerfile, agent.conf and cygnus-entrypoint.sh
* Dockerfile, agent.conf and cygnus-entrypoint.sh are edited to be able to use NGSIElasticsearchSink.
* The "ENV GIT_URL_CYGNUS" and "ENV GIT_REV_CYGNUS" are changed to "ARG" in order to be able to change git repository and branch through "docker build" command line.
* In order to stop cygnus container gracefully, trap SIGINT and SIGTERM signal and propagate it to the child cygnus-flume-ng agents.
    * By doing so, "org.apache.flume.sink.AbstractSink#stop" is called when the cygnus container will be stopped.

### CODE REVIEW

**Comment by nmatsui** [comment]
I'm sorry, I don't care about openjdk7. I'll fix my code to be able to compile openjdk7.

**Comment by fgalan** [comment]
@nmatsui any update in this PR, please? Don't hesitate of asking if something is not clear about what is pending in this PR to be finished and merged. Thanks!

**Comment by nmatsui** [comment]
@fgalan I pushed this PR half a year ago based on version 1.9. But this was not reviewed after that, so I thought that this was rejected. I will resolve the conflicts as soon as possible, and will push RP again.

**Comment by fgalan** [comment]
I sent you an email to the address that appears in your profile at https://github.com/nmatsui (at October 22nd, 2018) regarding IPR aspects. Did you receive it?

I apologize if I used a wrong email address and that has delayed this too much. In that case, could you tell me your right email address, pls? Thanks!

**Comment by nmatsui** [comment]
@fgalan I'm sorry but I can't find your mail. It may have been filtered. Could you please send the email again to the following addresses? 

nobuyuki.matsui@gmail.com, matsui.nobuyuki@tis.co.jp

Regards, Matsui

**Comment by nmatsui** [comment]
@fgalan I could receive your mail now! Thank you for your kindness. And I'll react your requests as soon as possible.
Regards, Matsui

**Comment by fgalan** [comment]
I have reviewed the PR after the recent changes. Thanks you for the contribution!

Some feedback:

* With regards to code, I think the PR is ok. You have incluced unit test for your sink, which is a necessary requirement. Perfect!
* With regards to documentation, you should include documentation corresponding to the new sink, please. You can have a look to some of the existing sinks documentation at https://github.com/telefonicaid/fiware-cygnus/tree/master/doc/cygnus-ngsi/flume_extensions_catalogue and create a ngsi_elasticsearch_sink.md file there which a similar structure and content (maybe the most important part is the table that describes the different configuration options). Apart from that file, some other places need to be adjusted:
    * Add an entry for the new file in the index at cygnus-ngsi/flume_extensions_catalogue/README.md (in the Sinks section)
    * Add the new file in mkdocs.yml (just after `'NGSIOrionSink'`)
    * Add entries for ElasticSearch in the bullet lists at README.md and cygnus-ngsi/README.md (just after Orion)
    * Add an entry in the "Features summary" table at cygnus-ngsi/README.md for NGSIElasticSearchSink and version 1.15.0.
* You have added a new backend, so I think corresponding documentation should be included. Please have a look to https://github.com/manucarrace/fiware-cygnus/tree/master/doc/cygnus-common/backends_catalogue and create a elasticsearch_backend.md file with a similar structure a content. Apart from that file, some other places need to be adjusted:
    * Add an entry for the new file in the index at cygnus-common/backends_catalogue/README.md (in the Sinks section)
    * Add the new file in mkdocs.yml (just after `'CartoDB backend'`)
* With regards to docker stuff (Dockerfile and entrypoint.sh), let us some more time to have a look. I'll check with my colleague @AlvaroVega which knows it better than me :)

By the way, it seems that a recent PR merge has caused a conflict in entrypoint.sh (sorry for the inconveniences). It would be great if you could solve it along with the rest of suggested changes.

**Comment by AlvaroVega** [comment]
LGTM

**Comment by AlvaroVega** [comment]
LGTM

**Comment by fgalan** [comment]
I forgot to mention...

Please add a line to CHANGEX_NEXT_RELEASE about this PR. Suggestion:

```
[cygnus-ngsi][ElasticSearch] Add ElasticSearch sink (#1516, #1521)
```

**Comment by nmatsui** [comment]
@fgalan @AlvaroVega Thanks for your responses. I'll write the necessary documents and will resolve conflict of `cygnus-entrypoint.sh` as soon as possible.

**Comment by nmatsui** [comment]
@fgalan I created or updated some documents like below:
* created
    * doc/cygnus-ngsi/flume_extensions_catalogue/ngsi_elasticsearch_sink.md
    * doc/cygnus-common/backends_catalogue/elasticsearch_backend.md
* updated
    * doc/cygnus-ngsi/flume_extensions_catalogue/README.md
    * doc/cygnus-common/backends_catalogue/README.md
    * cygnus-ngsi/README.md
    * README.md
    * mkdocs.yml
    * CHANGES_NEXT_RELEASE

And I found a potential bug of the index naming logic when writing above documents, so I fixed the bug of `NGSIElasticsearchSink` and wrote some tests.

**Pull request merged**
