### PR TITLE
feature/1101_add_spec_file_cygnus_twitter

### PR DESCRIPTION
**Pull request by javipalanca**
Added spec file for cygnus-twitter

### CODE REVIEW

**Comment by frbattid** [comment]
LGTM, passing the ball to @vgarciag since he is the one that will be using this file.

**Comment by vgarciag** [comment]
I tested the package of the Twitter component and it fails. 

This is due to in the [packaging script](https://github.com/telefonicaid/fiware-cygnus/blob/master/rpm/package.sh) there is a section to copy de config templates and a README.md file into destination directory: https://github.com/telefonicaid/fiware-cygnus/blob/master/rpm/package.sh#L108 

In the Twitter conf directory this `README.md` doesn't exists a thus provoque script failure. I think 2 possible solutions:

1. Add to the Twitter component the `README.md` file
2. Change script to consider this case for Twitter component.

I prefer the 1. option 😃

**Comment by frbattid** [comment]
I agree, let's add that README.md

**Comment by javipalanca** [comment]
Fixed in 906e813

**Comment by vgarciag** [comment]
LGTM

**Pull request merged**
