### PR TITLE
Update ArcgisFeatureTable.java

### PR DESCRIPTION
**Pull request by AlvaroVega**
https://hub.docker.com/repository/registry-1.docker.io/telefonicaiot/fiware-cygnus/builds/ad73e166-2a5a-46a2-bc1e-59704be67947

### CODE REVIEW

**Comment by AlvaroVega** [comment]
needs https://github.com/telefonicaid/fiware-cygnus/pull/2322

**Review by fgalan — APPROVED** [review]
LGTM

**Comment by fgalan** [comment]
Pending on @danielvillalbamota LGTM to be merged.

**Review by danielvillalbamota — APPROVED** [review]
LGTM

**Pull request merged**
