### PR TITLE
Upgrade flume version from 1.4 to 1.9

### PR DESCRIPTION
**Pull request by fgalan**
Fixes https://github.com/telefonicaid/fiware-cygnus/issues/1603

### CODE REVIEW

**Comment by AlvaroVega** [comment]
LGTM
I suggest delete this entry about Java 7: https://github.com/telefonicaid/fiware-cygnus/blob/master/.travis.yml#L4

**Comment by mrutid** [comment]
LGTM

**Comment by AlvaroVega** [comment]
@fgalan  Docker cygnus still has flume 1.4.0
https://github.com/telefonicaid/fiware-cygnus/blob/master/docker/cygnus-ngsi/Dockerfile#L190

**Comment by fgalan** [comment]
Let's change it and see how it crashes :) PR on the way...

**Comment by fgalan** [comment]
PR with the fix in Dockerfiles: https://github.com/telefonicaid/fiware-cygnus/pull/1611

**Pull request merged**
