### PR TITLE
hardening/407_remove_elements_length_checks

### PR DESCRIPTION
**Pull request by frbattid**
* Implements issue #407 
* 100% unit tests passed:
```
Tests run: 66, Failures: 0, Errors: 0, Skipped: 0 --> cygnus-common
Tests run: 98, Failures: 0, Errors: 0, Skipped: 0 --> cygnus-ngsi
```
* Assignee @pcoello25 but LGTM from @gtorodelvalle is also required

### CODE REVIEW

**Comment by gtorodelvalle** [comment]
Now if something happens when creating a database, table/collection/etc., because of its size, the Exception thrown by the corresponding driver is somehow sent back to the Context Broker in the response to its (notification) request... I guess as a `500 - Internal Server Error` HTTP code status, `statusCode` and `reasonPhrase`, right? :)

**Comment by frbattid** [comment]
Nothing is sent back to Orion, nor when the size was checked, nor now we rely in the storage driver/API for detecting and tracing the error. The main reason is Orion won't do anything with the error. Additionally, Cygnus (Flume) works by receiving the notification and always sending back `200 OK` (despite, as said, Orion does not take care about this), then temporarily buffering the data and finally processing it. As you can see, the reception and processing steps (where the error condition is detected) are decoupled, thus nothing can be sent back to Orion.

**Comment by gtorodelvalle** [comment]
Right, I forgot about Flume... :) So I guess Cygnus will log the error and maybe raise some kind of alarm (if enabled, I mean by the DevOps team)? :)

**Comment by frbattid** [comment]
Correct, a log is traced and then, if defined, an alarm is raised.

**Comment by gtorodelvalle** [comment]
Great! NTC :) LGTM from my side and passing it over to @pcoello25 for additional checking and merging... ;)

**Pull request closed without merging**
