### PR TITLE
hardening/fix_cygnusngsi_readme_contact

### PR DESCRIPTION
**Pull request by netzahdzc**

### CODE REVIEW

**Comment by fgalan** [comment]
LGTM

**Comment by netzahdzc** [comment]
no sure what does lgtm implies but, just in case, this is the section where you could found that the link is miss misdirected (contact section): https://github.com/telefonicaid/fiware-cygnus/tree/master/cygnus-ngsi

**Comment by fgalan** [comment]
LGTM stands for Look Good To Me. It is part of our internal review protocol ;) Don't worry, you'll PR will be merged soon.

Thanks for the contribution!

**Comment by netzahdzc** [comment]
ok ok :P

thanks :)

**Comment by frbattid** [comment]
LGTM

**Pull request merged**
