### PR TITLE
Task/json metadata

### PR DESCRIPTION
**Pull request by IvanHdzC**
This PR is related to #1902.

### CODE REVIEW

**Review by AlvaroVega — COMMENTED** [review]
A CNR update is needed

**Review by manucarrace — APPROVED** [review]

**Comment by IvanHdzC** [comment]
> A CNR update is needed

Fixed in [e4c21a1](https://github.com/telefonicaid/fiware-cygnus/pull/1919/commits/e4c21a1e396eb391d34e73cf3c711998e99f13b8)

**Comment by manucarrace** [comment]
Just a question. If I store metadata in a JsonArray object, does it mean that when I persist the data it will be stored between brackets? Even when there is a single metadata?

**Review by AlvaroVega — APPROVED** [review]
LGTM

**Comment by IvanHdzC** [comment]
> Just a question. If I store metadata in a JsonArray object, does it mean that when I persist the data it will be stored between square brackets? Even when there is a single metadata?

That's correct @manucarrace. It always be on square brackets.

**Comment by manucarrace** [comment]
LGTM

**Comment by AlvaroVega** [comment]
@IvanHdzC This log was reported after test it:

time=2020-09-03T13:51:09.462Z | lvl=INFO | corr=855996f0-edec-11ea-ae1e-fa163ec74401 | trans=439cf0b7-e70e-483e-b27e-ac17f6e06d8f | srv=dipbad | subsrv=/envAirQualityRESPIRA | op=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.NGSIRestHandler[306] : [NGSIRestHandler] Starting internal transaction (439cf0b7-e70e-483e-b27e-ac17f6e06d8f)
time=2020-09-03T13:51:09.464Z | lvl=INFO | corr=855996f0-edec-11ea-ae1e-fa163ec74401 | trans=439cf0b7-e70e-483e-b27e-ac17f6e06d8f | srv=dipbad | subsrv=/envAirQualityRESPIRA | op=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.NGSIRestHandler[324] : [NGSIRestHandler] Received data ({"subscriptionId":"5f475ac02d7063421980836a","originator":"localhost","contextResponses":[{"contextElement":{"type":"RESPIRA","isPattern":"false","id":"bada1","attributes":[{"name":"TimeInstant","type":"DateTime","value":"2020-07-01T20:32:06.000Z","metadatas":[{"name":"dateCreated","type":"DateTime","value":"2020-01-10T10:08:33.000Z"},{"name":"dateModified","type":"DateTime","value":"2020-07-08T10:55:38.000Z"}]},{"name":"airQualityIndex","type":"Number","value":31,"metadatas":[{"name":"dateCreated","type":"DateTime","value":"2020-01-10T10:08:33.000Z"},{"name":"dateModified","type":"DateTime","value":"2020-07-08T10:55:38.000Z"}]}]},"statusCode":{"code":"200","reasonPhrase":"OK"}}]})
time=2020-09-03T13:51:13.516Z | lvl=ERROR | corr=855996f0-edec-11ea-ae1e-fa163ec74401 | trans=439cf0b7-e70e-483e-b27e-ac17f6e06d8f | srv=dipbad | subsrv=/envAirQualityRESPIRA | op=processNewBatches | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.NGSISink[587] : java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2Stack trace: [com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176), com.google.gson.Gson.fromJson(Gson.java:795), com.google.gson.Gson.fromJson(Gson.java:761), com.google.gson.Gson.fromJson(Gson.java:710), com.google.gson.Gson.fromJson(Gson.java:682), com.telefonica.iot.cygnus.aggregation.NGSIGenericColumnAggregator.aggregate(NGSIGenericColumnAggregator.java:111), com.telefonica.iot.cygnus.sinks.NGSICKANSink.persistBatch(NGSICKANSink.java:285), com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches(NGSISink.java:569), com.telefonica.iot.cygnus.sinks.NGSISink.process(NGSISink.java:371), org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68), org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147), java.lang.Thread.run(Thread.java:748)]

**Pull request merged**
