### PR TITLE
[FIX] timestamp type is accepted in recvTime field

### PR DESCRIPTION
**Pull request by iariasleon**

### CODE REVIEW

**Comment by gtorodelvalle** [comment]
Assigning the PR to @frbattid for further checking :) Anyhow, LGTM on my side ;)

**Comment by gtorodelvalle** [comment]
BTW, I noticed you sent this PR to develop :) Should the milestone of the PR be set to some concrete milestone? In fact, I saw there are none available right now :)

**Comment by gtorodelvalle** [comment]
Just to be sure this code lands where it is supposed to land... :)

**Comment by frbattid** [comment]
About the fix, LGTM. About where to merge it... develop for sure, and maybe release/0.8.1? Since the timestamp stuff was fixed both in develop and release/0.8.1.

**Comment by iariasleon** [comment]
Yes, I think it should be in release/0.8.1 too

**Comment by XavierVal** [comment]
LGTM

**Pull request merged**
