### PR TITLE
bug/package_name_is_cygnus_rpm_file_name_is_cygnus_hadoopcore_x.y.z (into release 0.11.0)

### PR DESCRIPTION
**Pull request by vgarciag**
This PR solves Issue #652.

### CODE REVIEW

**Comment by frbattid** [comment]
An entry in CHANGES_NEXT_RELEASE is required.

**Comment by frbattid** [comment]
As @mrutid told us, this kind of changes must be asked to @mcarracedo for acknowledgement.

**Comment by manucarrace** [comment]
LGTM

**Comment by frbattid** [comment]
Add an entry in CHANGES_NEXT_RELEASE.

**Comment by frbattid** [comment]
LGTM

**Pull request merged**
