### PR TITLE
hardening/807_add_v1_GET_appenders_method

### PR DESCRIPTION
**Pull request by pcoello25**
* Partially fix issue #807 
* 100% unit test passed:
```
Results : Tests run: 69, Failures: 0, Errors: 0, Skipped: 0
```
* e2e (unofficial) tests passed:
```
$ curl -X GET "http://localhost:8081/v1/admin/log/appenders"
{"success":"true","appenders":[{"name":"console","layout":"time=%d{yyyy-MM-dd}T%d{HH:mm:ss.SSSzzz} | lvl=%p | corr=%X{correlatorId} | trans=%X{transactionId} | srv=%X{service} | subsrv=%X{subservice} | function=%M | comp=Cygnus | msg=%C[%L] : %m%n"}]}

$ curl -X GET "http://localhost:8081/v1/admin/log/appenders?transient=false"
{"success":"true","appenders":[{"name":"LOGFILE","layout":"time=%d{yyyy-MM-dd}T%d{HH:mm:ss.SSSzzz} | lvl=%p | corr=%X{correlatorId} | trans=%X{transactionId} | srv=%X{service} | subsrv=%X{subservice} | function=%M | comp=Cygnus | msg=%C[%L] : %m%n"}, {"name":"newAppender","layout":"anotherPattern"}, {"name":"console","layout":"time=%d{yyyy-MM-dd}T%d{HH:mm:ss.SSSzzz} | lvl=%p | corr=%X{correlatorId} | trans=%X{transactionId} | srv=%X{service} | subsrv=%X{subservice} | function=%M | comp=Cygnus | msg=%C[%L] : %m%n"}]}

$ curl -X GET "http://localhost:8081/v1/admin/log/appenders?name=LOGFILE"
{"success":"false","result":"Appender name not found"}

$ curl -X GET "http://localhost:8081/v1/admin/log/appenders?transient=false&name=LOGFILE"
{"success":"true","appender":[[{"name":"LOGFILE","layout":"time=%d{yyyy-MM-dd}T%d{HH:mm:ss.SSSzzz} | lvl=%p | corr=%X{correlatorId} | trans=%X{transactionId} | srv=%X{service} | subsrv=%X{subservice} | function=%M | comp=Cygnus | msg=%C[%L] : %m%n"}]}

$ curl -X GET "http://localhost:8081/v1/admin/log/appenders?transient=negative"
{"success":"false","result":{"Invalid 'transient' parameter found"}}
```
* Assignee: @frbattid

### CODE REVIEW

**Comment by frbattid** [comment]
An extra field per appender, "active":"true"|"false" would be required.

**Comment by pcoello25** [comment]
New logs with field `active`:
```
$ curl -X GET "http://localhost:8081/v1/admin/log/appenders"
{"success":"true","appender":[{"name":"console","layout":"time=%d{yyyy-MM-dd}T%d{HH:mm:ss.SSSzzz} | lvl=%p | corr=%X{correlatorId} | trans=%X{transactionId} | srv=%X{service} | subsrv=%X{subservice} | function=%M | comp=Cygnus | msg=%C[%L] : %m%n","active":"true"}]}

$ curl -X GET "http://localhost:8081/v1/admin/log/appenders?name=console"
{"success":"true","appender":[{"name":"console","layout":"time=%d{yyyy-MM-dd}T%d{HH:mm:ss.SSSzzz} | lvl=%p | corr=%X{correlatorId} | trans=%X{transactionId} | srv=%X{service} | subsrv=%X{subservice} | function=%M | comp=Cygnus | msg=%C[%L] : %m%n","active":"true"}]}

$ curl -X GET "http://localhost:8081/v1/admin/log/appenders?name=default"
{"success":"false","result":"Appender name not found"}

$ curl -X GET "http://localhost:8081/v1/admin/log/appenders?transient=false"
{"success":"true","appenders":[{"name":"LOGFILE","layout":"time=%d{yyyy-MM-dd}T%d{HH:mm:ss.SSSzzz} | lvl=%p | corr=%X{correlatorId} | trans=%X{transactionId} | srv=%X{service} | subsrv=%X{subservice} | function=%M | comp=Cygnus | msg=%C[%L] : %m%n","active":"true"}, {"name":"newAppender","layout":"anotherPattern","active":"false"}, {"name":"console","layout":"time=%d{yyyy-MM-dd}T%d{HH:mm:ss.SSSzzz} | lvl=%p | corr=%X{correlatorId} | trans=%X{transactionId} | srv=%X{service} | subsrv=%X{subservice} | function=%M | comp=Cygnus | msg=%C[%L] : %m%n","active":"false"}]}

$ curl -X GET "http://localhost:8081/v1/admin/log/appenders?transient=false&name=LOGFILE"
{"success":"true","appender":[{"name":"LOGFILE","layout":"time=%d{yyyy-MM-dd}T%d{HH:mm:ss.SSSzzz} | lvl=%p | corr=%X{correlatorId} | trans=%X{transactionId} | srv=%X{service} | subsrv=%X{subservice} | function=%M | comp=Cygnus | msg=%C[%L] : %m%n","active":"true"}]}

$ curl -X GET "http://localhost:8081/v1/admin/log/appenders?transient=false&name=console"
{"success":"true","appender":[{"name":"console","layout":"time=%d{yyyy-MM-dd}T%d{HH:mm:ss.SSSzzz} | lvl=%p | corr=%X{correlatorId} | trans=%X{transactionId} | srv=%X{service} | subsrv=%X{subservice} | function=%M | comp=Cygnus | msg=%C[%L] : %m%n","active":"false"}]}

$ curl -X GET "http://localhost:8081/v1/admin/log/appenders?transient=default&name=console"
{"success":"false","result":"Invalid 'transient' parameter found"}

$ curl -X GET "http://localhost:8081/v1/admin/log/appenders?transient=false&name=default"
{"success":"false","result":"Appender name not found"}

```

**Comment by pcoello25** [comment]
@frbattid , your request has been fixed in  459385a :)

**Comment by frbattid** [comment]
LGTM

**Pull request merged**
