### PR TITLE
Modified to accept IP as string

### PR DESCRIPTION
**Pull request by MadhuNEC**
Fixes issue #2226 .

### CODE REVIEW

**Comment by fgalan** [comment]
Thanks for your contribution!

Could you elaborate a little bit in which way this PR solves issue #2228?

**Comment by MadhuNEC** [comment]
Hi @fgalan,

Whenever an IP is notified in the attribute, cygnus tries to add the aggregated data. And at [code](https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSISTHSink.java#L341), isANumber() returns true. 
But [update()](https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSISTHSink.java#L349) fails as it cannot recognize IP(192.168.56.101) as a valid Double.

A number having multiple decimal cannot be qualified as valid Number.

So, I have updated the isANumber() to return false if an IP is passed as an argument. Then the IP attribute will be stored as String [here](https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSISTHSink.java#L351).

Please let me know if you have any concern.

**Comment by MadhuNEC** [comment]
Hi @fgalan,

Whenever an IP is notified in the attribute, cygnus tries to add the aggregated data. And at [code](https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSISTHSink.java#L341), isANumber() returns true. 
But [update()](https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSISTHSink.java#L349) fails as it cannot recognize IP(192.168.56.101) as a valid Double.

A number having multiple decimal cannot be qualified as valid Number.

So, I have updated the isANumber() to return false if an IP is passed as an argument. Then the IP attribute will be stored as String [here](https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSISTHSink.java#L351).

Please let me know if you have any concern.

**Comment by AlvaroVega** [comment]
Could you please add some unit tests about these cases to https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-common/src/test/java/com/telefonica/iot/cygnus/utils/CommonUtilsTest.java ? Thanks in advance!

**Comment by MadhuNEC** [comment]
> Could you please add some unit tests about these cases to https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-common/src/test/java/com/telefonica/iot/cygnus/utils/CommonUtilsTest.java ? Thanks in advance!

Hi @AlvaroVega ,

I could not find any existing test cases for isANumber() in https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-common/src/test/java/com/telefonica/iot/cygnus/utils/CommonUtilsTest.java. 

Do I need to create new test cases for isANumber()?

**Comment by fgalan** [comment]
> I could not find any existing test cases for isANumber() in https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-common/src/test/java/com/telefonica/iot/cygnus/utils/CommonUtilsTest.java.
> 
> Do I need to create new test cases for isANumber()?

Although we don't currently have test cases for isANumber() I think it would be a good addition. In general, when we have a PR that "touches" a not test-covered part in the code is a good idea to add tests to cover it.

**Comment by MadhuNEC** [comment]
> Although we don't currently have test cases for isANumber() I think it would be a good addition. In general, when we have a PR that "touches" a not test-covered part in the code is a good idea to add tests to cover it.

Hi @fgalan , @AlvaroVega ,

Thanks for the support.
I have updated the test cases for isANumber().

**Comment by fgalan** [comment]
Now that we have the `isANumber(String s)` function covered by unit tests (thanks for that @MadhuNEC ! :) it would be great to replace that somehow ah hoc function for some Java standard function. For instance, something similar to the one shown at https://stackoverflow.com/a/5439547/1485926:

```java
public static boolean isInteger(String s) {
    try { 
        Integer.parseInt(s); 
    } catch(NumberFormatException e) { 
        return false; 
    } catch(NullPointerException e) {
        return false;
    }
    // only got here if we didn't return false
    return true;
}
```

But adapting it a little bit to cover also float numbers.

The `isANumber(String s, int radix)` auxiliary function (the one with two arguments) could be probably removed.

**Comment by MadhuNEC** [comment]
> Now that we have the `isANumber(String s)` function covered by unit tests (thanks for that @MadhuNEC ! :) it would be great to replace that somehow ah hoc function for some Java standard function. For instance, something similar to the one shown at https://stackoverflow.com/a/5439547/1485926:
> 
> ```java
> public static boolean isInteger(String s) {
>     try { 
>         Integer.parseInt(s); 
>     } catch(NumberFormatException e) { 
>         return false; 
>     } catch(NullPointerException e) {
>         return false;
>     }
>     // only got here if we didn't return false
>     return true;
> }
> ```
> 
> But adapting it a little bit to cover also float numbers.
> 
> The `isANumber(String s, int radix)` auxiliary function (the one with two arguments) could be probably removed.
> 
> _Edit_: a function comparible with Java 11, as Java 8 to 10 are going to be deprecated soon in Cygnus

Hi @fgalan,

It will be difficult to cover Float and Decimal with this approach.
I have a different approach using Pattern matching. Please find below approach and share your opinion:
```
	public boolean isANumber(String s) {
              Pattern pattern = Pattern.compile("-?\\d+(\\.\\d+)?");
               if (s==null) {
        	   return false;
               }
               return pattern.matcher(s).matches();
	}
```

I have verified that it is producing positive result for below data:
isANumber("10.0"); //true
isANumber("-10.0"); //true
isANumber("10"); //true
isANumber("-10"); //true
isANumber("0.abc"); //false
isANumber("abc"); //false
isANumber("127.0.0.1"); //false

**Comment by fgalan** [comment]
> It will be difficult to cover Float and Decimal with this approach.

Has you tried with `Float.parseFloat(s) (https://w3api.com/Java/Float/parseFloat)?

**Comment by MadhuNEC** [comment]
> > It will be difficult to cover Float and Decimal with this approach.
> 
> Has you tried with `Float.parseFloat(s)` (https://w3api.com/Java/Float/parseFloat)?

Hi @fgalan,
Yes, I have checked it with Float.parseFloat(s) and Double.parseDouble(s).
As per my understanding, Double.parseDouble(s) will be good implementation because we are saving the attrValue as Double [here](https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSISTHSink.java#L349).
Please find below block:
```
    public static boolean isANumber(String s) {
        try {
            Double.parseDouble(s);
        } catch (NumberFormatException e){
            return false;
        } catch (NullPointerException e) {
            return false;
        }
        return true;
    } // isANumber
```

And we should remove `isANumber(String s, int radix)` as it will not be needed.

**Comment by fgalan** [comment]
> > > It will be difficult to cover Float and Decimal with this approach.
> > 
> > 
> > Has you tried with `Float.parseFloat(s)` (https://w3api.com/Java/Float/parseFloat)?
> 
> Hi @fgalan, Yes, I have checked it with Float.parseFloat(s) and Double.parseDouble(s). As per my understanding, Double.parseDouble(s) will be good implementation because we are saving the attrValue as Double [here](https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSISTHSink.java#L349). Please find below block:
> 
> ```
>     public static boolean isANumber(String s) {
>         try {
>             Double.parseDouble(s);
>         } catch (NumberFormatException e){
>             return false;
>         } catch (NullPointerException e) {
>             return false;
>         }
>         return true;
>     } // isANumber
> ```
> 
> And we should remove `isANumber(String s, int radix)` as it will not be needed.

Sounds good! :)

I'd suggest to apply that code and check if tests work with it.

**Comment by MadhuNEC** [comment]
> Sounds good! :)
> 
> I'd suggest to apply that code and check if tests work with it.

Hi @fgalan ,

I have updated the code.

**Comment by MadhuNEC** [comment]
Hi @fgalan,

I request you to please merge the PR, if it seems fine.

Thanks.

**Review by fgalan — APPROVED** [review]
LGTM

Thanks for the contribution!

**Pull request merged**
